### ISSUE TITLE
Check your local git config

### ISSUE THREAD

**Issue by zkamvar** [carpentries-incubator/statistical-probabilistic-programming-r#1]
Hello @velait, I noticed you are making commits as @carpentries-bot in this repo, which means that you have run into this bug: https://github.com/carpentries/sandpaper/issues/449

Can you provide the steps you took to updating your lesson? I'm trying to figure out how this bug appears.

**Comment by velait** [comment]
Hi,

The way I've worked on the lesson material is simply by using the provided template and running sandpaper::serve() to build the lesson. I have this command (and nothing else) written in a separate R script that I source to run it.

I'm using acOS 12.5 (Monterey), RStudio version 2022.12.0+353 and below you'll find the session info and config.yaml.

I hope this helps and I'm happy to provide additional information if needed.

Ville

<details><summary>session info</summary>

************ session info:

R version 4.2.2 (2022-10-31)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.5

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] tinkr_0.1.0.9000 pegboard_0.4.3   varnish_0.2.15   sandpaper_0.11.8

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.10       later_1.3.0       compiler_4.2.2    pillar_1.8.1      tools_4.2.2       sys_3.4.1
 [7] downlit_0.4.2     digest_0.6.31     jsonlite_1.8.4    memoise_2.0.1     evaluate_0.19     lifecycle_1.0.3
[13] tibble_3.1.8      pkgconfig_2.0.3   rlang_1.0.6       cli_3.6.0         rstudioapi_0.14   commonmark_1.8.1
[19] yaml_2.3.6        pkgdown_2.0.7     xfun_0.36         fastmap_1.1.0     withr_2.5.0       dplyr_1.1.0
[25] xml2_1.3.3        knitr_1.41        desc_1.4.2        generics_0.1.3    fs_1.5.2          vctrs_0.5.2
[31] askpass_1.1       tidyselect_1.2.0  rprojroot_2.0.3   gert_1.9.2        glue_1.6.2        R6_2.5.1
[37] processx_3.8.0    fansi_1.0.3       rmarkdown_2.19    servr_0.25        callr_3.7.3       purrr_1.0.1
[43] magrittr_2.0.3    whisker_0.4.1     promises_1.2.0.1  ps_1.7.2          credentials_1.3.2 htmltools_0.5.4
[49] assertthat_0.2.1  xslt_1.4.4        mime_0.12         httpuv_1.6.9      renv_0.17.0-38    utf8_1.2.2
[55] openssl_2.0.5     cachem_1.0.6


</details> 

<details><summary>config.yaml</summary>

************ config.yaml

#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------

# Which carpentry is this (swc, dc, lc, or cp)?
# swc: Software Carpentry
# dc: Data Carpentry
# lc: Library Carpentry
# cp: Carpentries (to use for instructor training for instance)
# incubator: The Carpentries Incubator
carpentry: 'incubator'

# Overall title for pages.
title: 'Statistical and Probabilistic Programming'

# Date the lesson was created (YYYY-MM-DD, this is empty by default)
created: ~

# Comma-separated list of keywords for the lesson
keywords: 'software, data, lesson, The Carpentries'

# Life cycle stage of the lesson
# possible values: pre-alpha, alpha, beta, stable
life_cycle: 'pre-alpha'

# License of the lesson
license: 'CC-BY 4.0'

# Link to the source repository for this lesson
source: 'https://github.com/carpentries-incubator/statistical-probabilistic-programming-r'

# Default branch of your lesson
branch: 'main'

# Who to contact if there are any issues
contact: ***@***.***'

# Navigation ------------------------------------------------
#
# Use the following menu items to specify the order of
# individual pages in each dropdown section. Leave blank to
# include all pages in the folder.
#
# Example -------------
#
# episodes:
# - introduction.md
# - first-steps.md
#
# learners:
# - setup.md
#
# instructors:
# - instructor-notes.md
#
# profiles:
# - one-learner.md
# - another-learner.md

# Order of episodes in your lesson
episodes:
- setup.Rmd
- bayesian-statistics.Rmd
- sampling.Rmd
- stan.Rmd
- mcmc.Rmd
- hierarchical-models.Rmd
- model-checking.Rmd
- advanced-topics.Rmd


# Information for Learners
learners:

# Information for Instructors
instructors:

# Learner Profiles
profiles:

# Customisation ---------------------------------------------
#
# This space below is where custom yaml items (e.g. pinning
# sandpaper and varnish versions) should live


</details> 




________________________________________
Lähettäjä: Zhian N. Kamvar ***@***.***>
Lähetetty: perjantai 26. toukokuuta 2023 22.07.33
Vastaanottaja: carpentries-incubator/statistical-probabilistic-programming-r
Kopio: Ville Laitinen; Mention
Aihe: [carpentries-incubator/statistical-probabilistic-programming-r] Check your local git config (Issue #1)

Hello @velait<https://github.com/velait>, I noticed you are making commits as @carpentries-bot<https://github.com/carpentries-bot> in this repo, which means that you have run into this bug: carpentries/sandpaper#449<https://github.com/carpentries/sandpaper/issues/449>

Can you provide the steps you took to updating your lesson? I'm trying to figure out how this bug appears.

**Comment by zkamvar** [comment]
> The way I've worked on the lesson material is simply by using the provided template and running sandpaper::serve() to build the lesson. I have this command (and nothing else) written in a separate R script that I source to run it.

Thank you for the information. I have a couple of followup questions and actions that will help me track down the reason why the issue is happening: 

1. How did you clone the repository to your computer? Did you use `git clone`?
2. What version of git do you have (`git --version`)? 
3. Can you open R inside your local copy of the repository and run the following code?
   ```r
   library("tibble") # for easy printing of the config table
   print(gert::libgit2_config())
   print(gert::git_config(), n = Inf)
   ```
4. Can you make a fresh, temporary clone and run the above R code in your freshly cloned repository? 

Here is my output from a fresh clone: 

<details><summary>Details</summary>

```sh
$ git --version
git version 2.40.1
```


``` r
library(tibble)
print(gert::libgit2_config())
#> $version
#> [1] '1.4.2'
#> 
#> $ssh
#> [1] TRUE
#> 
#> $https
#> [1] TRUE
#> 
#> $threads
#> [1] TRUE
#> 
#> $config.global
#> [1] "/home/zhian/.gitconfig"
#> 
#> $config.system
#> [1] ""
#> 
#> $config.home
#> [1] "/home/zhian"
print(gert::git_config(), n = Inf)
#> # A tibble: 25 × 3
#>    name                         value                                      level
#>  * <chr>                        <chr>                                      <chr>
#>  1 user.name                    Zhian N. Kamvar                            glob…
#>  2 user.email                   zkamvar@gmail.com                          glob…
#>  3 user.signinkey               727EEF9661F68EA5                           glob…
#>  4 include.path                 ~/Documents/config-files/.gitconfig        glob…
#>  5 init.defaultbranch           main                                       glob…
#>  6 pull.rebase                  false                                      glob…
#>  7 color.ui                     true                                       glob…
#>  8 alias.lg                     !git lg1                                   glob…
#>  9 alias.lg1                    !git lg1-specific --exclude=*/md-outputs*… glob…
#> 10 alias.lg2                    !git lg2-specific --exclude=*/md-outputs*… glob…
#> 11 alias.lg3                    !git lg3-specific --exclude=*/md-outputs*… glob…
#> 12 alias.lg1-specific           log     --graph     --abbrev-commit     -… glob…
#> 13 alias.lg2-specific           log     --graph     --abbrev-commit     -… glob…
#> 14 alias.lg3-specific           log     --graph     --decorate     --form… glob…
#> 15 alias.pushb                  !git push --set-upstream $(git remote | h… glob…
#> 16 credential.helper            /usr/share/doc/git/contrib/credential/gno… glob…
#> 17 commit.gpgsign               true                                       glob…
#> 18 core.bare                    false                                      local
#> 19 core.repositoryformatversion 0                                          local
#> 20 core.filemode                true                                       local
#> 21 core.logallrefupdates        true                                       local
#> 22 remote.origin.url            https://github.com/carpentries/sandpaper-… local
#> 23 remote.origin.fetch          +refs/heads/*:refs/remotes/origin/*        local
#> 24 branch.main.remote           origin                                     local
#> 25 branch.main.merge            refs/heads/main                            local
```

<sup>Created on 2023-05-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
</details>

**Comment by velait** [comment]
Hi,

1. I cloned with git clone in Terminal.

2. My git version is 2.37.1 (Apple Git-137.1)

3.

> print(gert::libgit2_config())
$version
[1] ‘1.4.2’

$ssh
[1] TRUE

$https
[1] TRUE

$threads
[1] TRUE

$config.global
[1] ""

$config.system
[1] ""

$config.home
[1] "/Users/villelaitinen"



> print(gert::git_config(), n = Inf)
# A tibble: 12 × 3
   name                         value                                                   level
 * <chr>                        <chr>                                                   <chr>
 1 core.repositoryformatversion 0                                                       local
 2 core.filemode                true                                                    local
 3 core.bare                    false                                                   local
 4 core.logallrefupdates        true                                                    local
 5 core.ignorecase              true                                                    local
 6 core.precomposeunicode       true                                                    local
 7 remote.origin.url            ***@***.***:carpentries-incubator/statistical-proba… local
 8 remote.origin.fetch          +refs/heads/*:refs/remotes/origin/*                     local
 9 branch.main.remote           origin                                                  local
10 branch.main.merge            refs/heads/main                                         local
11 user.name                    carpenter                                               local
12 user.email                   ***@***.***                                    local


4.

> print(gert::libgit2_config())
$version
[1] ‘1.4.2’

$ssh
[1] TRUE

$https
[1] TRUE

$threads
[1] TRUE

$config.global
[1] ""

$config.system
[1] ""

$config.home
[1] "/Users/villelaitinen"

> print(gert::git_config(), n = Inf)
# A tibble: 10 × 3
   name                         value                                                   level
 * <chr>                        <chr>                                                   <chr>
 1 core.repositoryformatversion 0                                                       local
 2 core.filemode                true                                                    local
 3 core.bare                    false                                                   local
 4 core.logallrefupdates        true                                                    local
 5 core.ignorecase              true                                                    local
 6 core.precomposeunicode       true                                                    local
 7 remote.origin.url            ***@***.***:carpentries-incubator/statistical-proba… local
 8 remote.origin.fetch          +refs/heads/*:refs/remotes/origin/*                     local
 9 branch.main.remote           origin                                                  local
10 branch.main.merge            refs/heads/main                                         local
________________________________________
Lähettäjä: Zhian N. Kamvar ***@***.***>
Lähetetty: maanantai 29. toukokuuta 2023 19.08.46
Vastaanottaja: carpentries-incubator/statistical-probabilistic-programming-r
Kopio: Ville Laitinen; Mention
Aihe: Re: [carpentries-incubator/statistical-probabilistic-programming-r] Check your local git config (Issue #1)

The way I've worked on the lesson material is simply by using the provided template and running sandpaper::serve() to build the lesson. I have this command (and nothing else) written in a separate R script that I source to run it.

Thank you for the information. I have a couple of followup questions and actions that will help me track down the reason why the issue is happening:

  1.  How did you clone the repository to your computer? Did you use git clone?
  2.  What version of git do you have (git --version)?
  3.  Can you open R inside your local copy of the repository and run the following code?

library("tibble") # for easy printing of the config table
print(gert::libgit2_config())
print(gert::git_config(), n = Inf)

  4.  Can you make a fresh, temporary clone and run the above R code in your freshly cloned repository?

Here is my output from a fresh clone:

Details

$ git --version
git version 2.40.1

library(tibble)
print(gert::libgit2_config())
#> $version
#> [1] '1.4.2'
#>
#> $ssh
#> [1] TRUE
#>
#> $https
#> [1] TRUE
#>
#> $threads
#> [1] TRUE
#>
#> $config.global
#> [1] "/home/zhian/.gitconfig"
#>
#> $config.system
#> [1] ""
#>
#> $config.home
#> [1] "/home/zhian"
print(gert::git_config(), n = Inf)
#> # A tibble: 25 × 3
#>    name                         value                                      level
#>  * <chr>                        <chr>                                      <chr>
#>  1 user.name                    Zhian N. Kamvar                            glob…
#>  2 user.email                   ***@***.***                          glob…
#>  3 user.signinkey               727EEF9661F68EA5                           glob…
#>  4 include.path                 ~/Documents/config-files/.gitconfig        glob…
#>  5 init.defaultbranch           main                                       glob…
#>  6 pull.rebase                  false                                      glob…
#>  7 color.ui                     true                                       glob…
#>  8 alias.lg                     !git lg1                                   glob…
#>  9 alias.lg1                    !git lg1-specific --exclude=*/md-outputs*… glob…
#> 10 alias.lg2                    !git lg2-specific --exclude=*/md-outputs*… glob…
#> 11 alias.lg3                    !git lg3-specific --exclude=*/md-outputs*… glob…
#> 12 alias.lg1-specific           log     --graph     --abbrev-commit     -… glob…
#> 13 alias.lg2-specific           log     --graph     --abbrev-commit     -… glob…
#> 14 alias.lg3-specific           log     --graph     --decorate     --form… glob…
#> 15 alias.pushb                  !git push --set-upstream $(git remote | h… glob…
#> 16 credential.helper            /usr/share/doc/git/contrib/credential/gno… glob…
#> 17 commit.gpgsign               true                                       glob…
#> 18 core.bare                    false                                      local
#> 19 core.repositoryformatversion 0                                          local
#> 20 core.filemode                true                                       local
#> 21 core.logallrefupdates        true                                       local
#> 22 remote.origin.url            https://github.com/carpentries/sandpaper-… local
#> 23 remote.origin.fetch          +refs/heads/*:refs/remotes/origin/*        local
#> 24 branch.main.remote           origin                                     local
#> 25 branch.main.merge            refs/heads/main                            local

Created on 2023-05-29 with reprex v2.0.2<https://reprex.tidyverse.org>

**Comment by zkamvar** [comment]
> 
> ```
> # A tibble: 10 × 3
>    name                         value                                                   level
>  * <chr>                        <chr>                                                   <chr>
>  1 core.repositoryformatversion 0                                                       local
>  2 core.filemode                true                                                    local
>  3 core.bare                    false                                                   local
>  4 core.logallrefupdates        true                                                    local
>  5 core.ignorecase              true                                                    local
>  6 core.precomposeunicode       true                                                    local
>  7 remote.origin.url            ***@***.***:carpentries-incubator/statistical-proba… local
>  8 remote.origin.fetch          +refs/heads/*:refs/remotes/origin/*                     local
>  9 branch.main.remote           origin                                                  local
> 10 branch.main.merge            refs/heads/main                                         local
> ```

Oh I see! For some reason {gert} is not detecting that you have a `user.name` or `user.email` set up for git. 


When you run `git config --global --list` from your terminal, do you get `user.name` and `user.email` values? If you do not, you should set those up as described in [Setting Up Git](https://swcarpentry.github.io/git-novice/02-setup.html). After that, you should remove the carpenter email and user name from the the local `statistical-probabalistic-programming-r/.git/config` file to have git use your credentials.

**Comment by velait** [comment]
Hi,

Hmm I made the changes but it still seems that I'm making commits as @carpentries-bot.

Running git config --global --list gives

user.name=Ville Laitinen
***@***.***

My statistical-probabalistic-programming-r/.git/config file now looks like this:

[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
        ignorecase = true
        precomposeunicode = true
[remote "origin"]
        url = ***@***.***:openresearchlabs/STPP.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "main"]
        remote = origin
        merge = refs/heads/main
[user]
        name = Ville Laitinen
        email = ***@***.***




________________________________________
Lähettäjä: Zhian N. Kamvar ***@***.***>
Lähetetty: tiistai 30. toukokuuta 2023 16.28.37
Vastaanottaja: carpentries-incubator/statistical-probabilistic-programming-r
Kopio: Ville Laitinen; Mention
Aihe: Re: [carpentries-incubator/statistical-probabilistic-programming-r] Check your local git config (Issue #1)

# A tibble: 10 × 3
   name                         value                                                   level
 * <chr>                        <chr>                                                   <chr>
 1 core.repositoryformatversion 0                                                       local
 2 core.filemode                true                                                    local
 3 core.bare                    false                                                   local
 4 core.logallrefupdates        true                                                    local
 5 core.ignorecase              true                                                    local
 6 core.precomposeunicode       true                                                    local
 7 remote.origin.url            ***@***.***:carpentries-incubator/statistical-proba… local
 8 remote.origin.fetch          +refs/heads/*:refs/remotes/origin/*                     local
 9 branch.main.remote           origin                                                  local
10 branch.main.merge            refs/heads/main                                         local


Oh I see! For some reason {gert} is not detecting that you have a user.name or user.email set up for git.

When you run git config --global --list from your terminal, do you get user.name and user.email values? If you do not, you should set those up as described in Setting Up Git<https://swcarpentry.github.io/git-novice/02-setup.html>. After that, you should remove the carpenter email and user name from the the local statistical-probabalistic-programming-r/.git/config file to have git use your credentials.

**Comment by zkamvar** [comment]
I'm sorry this is still an issue. I've added a fix that should address this. Could you test this out by installing the patch in https://github.com/carpentries/sandpaper/pull/476: 

```r
# install.packages("pak")
pak::pkg_install("carpentries/sandpaper#476")
```

After that, run the code in https://github.com/carpentries-incubator/statistical-probabilistic-programming-r/issues/1#issuecomment-1567313884 and see if it works.

**Comment by velait** [comment]
Hi,

Seems that the issue is no longer there!

Thanks, Ville
________________________________________
Lähettäjä: Zhian N. Kamvar ***@***.***>
Lähetetty: torstai 1. kesäkuuta 2023 20.38.59
Vastaanottaja: carpentries-incubator/statistical-probabilistic-programming-r
Kopio: Ville Laitinen; Mention
Aihe: Re: [carpentries-incubator/statistical-probabilistic-programming-r] Check your local git config (Issue #1)

I'm sorry this is still an issue. I've added a fix that should address this. Could you test this out by installing the patch in carpentries/sandpaper#476<https://github.com/carpentries/sandpaper/pull/476>:

# install.packages("pak")
pak::pkg_install("carpentries/sandpaper#476")

After that, run the code in #1 (comment)<https://github.com/carpentries-incubator/statistical-probabilistic-programming-r/issues/1#issuecomment-1567313884> and see if it works.

**Comment by zkamvar** [comment]
Thank you for following up! I will merge the PR in that case since it may help prevent this issue in the first place!
